[project]
name = "jplaw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "jq>=1.11.0",
]
